const wordList = [
  // Unit 1
  { unit: 1, group: 1, word: "get up", meaning: "起床", phonetic: "" },
  { unit: 1, group: 1, word: "have breakfast", meaning: "吃早餐", phonetic: "" },
  { unit: 1, group: 1, word: "go to school", meaning: "上学", phonetic: "" },
  { unit: 1, group: 1, word: "have lunch", meaning: "吃午餐", phonetic: "" },
  { unit: 1, group: 1, word: "go home", meaning: "回家", phonetic: "" },
  { unit: 1, group: 2, word: "have dinner", meaning: "吃晚餐", phonetic: "" },
  { unit: 1, group: 2, word: "go to bed", meaning: "睡觉", phonetic: "" },
  { unit: 1, group: 2, word: "daily", meaning: "每日的", phonetic: "" },
  { unit: 1, group: 2, word: "schedule", meaning: "日程安排", phonetic: "" },
  { unit: 1, group: 2, word: "at", meaning: "在", phonetic: "" },
  { unit: 1, group: 3, word: "o'clock", meaning: "点钟", phonetic: "" },
  { unit: 1, group: 3, word: "half", meaning: "点半", phonetic: "" },
  { unit: 1, group: 3, word: "little", meaning: "年幼的", phonetic: "" },
  { unit: 1, group: 3, word: "drink", meaning: "喝", phonetic: "" },
  { unit: 1, group: 3, word: "lesson", meaning: "课", phonetic: "" },
  { unit: 1, group: 4, word: "draw", meaning: "画", phonetic: "" },
  { unit: 1, group: 4, word: "quarter", meaning: "15分钟;一刻钟", phonetic: "" },
  { unit: 1, group: 4, word: "Miss", meaning: "小姐", phonetic: "" },
  { unit: 1, group: 4, word: "brush my teeth", meaning: "刷牙", phonetic: "" },
  { unit: 1, group: 4, word: "wash my face", meaning: "洗脸", phonetic: "" },
  

  // Unit 2
  { unit: 2, group: 1, word: "Chinese", meaning: "语文", phonetic: "" },
  { unit: 2, group: 1, word: "Maths", meaning: "数学", phonetic: "" },
  { unit: 2, group: 1, word: "English", meaning: "英语", phonetic: "" },
  { unit: 2, group: 1, word: "PE", meaning: "体育", phonetic: "" },
  { unit: 2, group: 1, word: "Music", meaning: "音乐", phonetic: "" },
  { unit: 2, group: 2, word: "Art", meaning: "美术", phonetic: "" },
  { unit: 2, group: 2, word: "IT", meaning: "信息技术", phonetic: "" },
  { unit: 2, group: 2, word: "Science", meaning: "科学", phonetic: "" },
  { unit: 2, group: 2, word: "club", meaning: "俱乐部;社团", phonetic: "" },
  { unit: 2, group: 2, word: "student", meaning: "学生", phonetic: "" },
  { unit: 2, group: 3, word: "different", meaning: "不同的", phonetic: "" },
  { unit: 2, group: 3, word: "subject", meaning: "科目", phonetic: "" },
  { unit: 2, group: 3, word: "class", meaning: "课;班级", phonetic: "" },
  { unit: 2, group: 3, word: "pig", meaning: "猪", phonetic: "" },
  { unit: 2, group: 3, word: "timetable", meaning: "时间表", phonetic: "" },
  { unit: 2, group: 4, word: "raise the national flag", meaning: "升国旗", phonetic: "" },
  { unit: 2, group: 4, word: "work out", meaning: "解决;算出", phonetic: "" },
  { unit: 2, group: 4, word: "after school", meaning: "放学后", phonetic: "" },
  { unit: 2, group: 4, word: "put on a play", meaning: "演出戏剧", phonetic: "" },
  { unit: 2, group: 4, word: "model plane", meaning: "飞机模型", phonetic: "" },
  { unit: 2, group: 5, word: "Great!", meaning: "太棒了", phonetic: "" },

  // Unit 3
  { unit: 3, group: 1, word: "firefighter", meaning: "消防员", phonetic: "" },
  { unit: 3, group: 1, word: "police officer", meaning: "警察", phonetic: "" },
  { unit: 3, group: 1, word: "farmer", meaning: "农夫", phonetic: "" },
  { unit: 3, group: 1, word: "teacher", meaning: "老师", phonetic: "" },
  { unit: 3, group: 1, word: "doctor", meaning: "医生", phonetic: "" },
  { unit: 3, group: 2, word: "bus driver", meaning: "公交车司机", phonetic: "" },
  { unit: 3, group: 2, word: "fire", meaning: "火", phonetic: "" },
  { unit: 3, group: 2, word: "sick", meaning: "生病的", phonetic: "" },
  { unit: 3, group: 2, word: "soup", meaning: "汤", phonetic: "" },
  { unit: 3, group: 2, word: "Mrs", meaning: "夫人;太太", phonetic: "" },
  { unit: 3, group: 3, word: "job", meaning: "工作;职业", phonetic: "" },
  { unit: 3, group: 3, word: "people", meaning: "人", phonetic: "" },
  { unit: 3, group: 3, word: "know", meaning: "知道", phonetic: "" },
  { unit: 3, group: 3, word: "dentist", meaning: "牙医", phonetic: "" },
  { unit: 3, group: 3, word: "or", meaning: "或者", phonetic: "" },
  { unit: 3, group: 4, word: "sweet", meaning: "甜的", phonetic: "" },
  { unit: 3, group: 4, word: "check", meaning: "检查", phonetic: "" },
  { unit: 3, group: 4, word: "hospital", meaning: "医院", phonetic: "" },
  { unit: 3, group: 4, word: "nurse", meaning: "护士", phonetic: "" },
  { unit: 3, group: 4, word: "put out fires", meaning: "灭火", phonetic: "" },
  { unit: 3, group: 5, word: "look after", meaning: "照顾", phonetic: "" },
  { unit: 3, group: 5, word: "twice or three times", meaning: "两次或三次", phonetic: "" },
  { unit: 3, group: 5, word: "fill holes in teeth", meaning: "补牙", phonetic: "" },
  { unit: 3, group: 5, word: "pull bad teeth out", meaning: "拔蛀牙", phonetic: "" },

  // Unit 4
  { unit: 4, group: 1, word: "triangle", meaning: "三角铁", phonetic: "" },
  { unit: 4, group: 1, word: "violin", meaning: "小提琴", phonetic: "" },
  { unit: 4, group: 1, word: "piano", meaning: "钢琴", phonetic: "" },
  { unit: 4, group: 1, word: "guitar", meaning: "吉他", phonetic: "" },
  { unit: 4, group: 1, word: "erhu", meaning: "二胡", phonetic: "" },
  { unit: 4, group: 2, word: "flute", meaning: "长笛", phonetic: "" },
  { unit: 4, group: 2, word: "pipa", meaning: "琵琶", phonetic: "" },
  { unit: 4, group: 2, word: "drum", meaning: "鼓", phonetic: "" },
  { unit: 4, group: 2, word: "woman", meaning: "成年女子", phonetic: "" },
  { unit: 4, group: 2, word: "concert", meaning: "音乐会", phonetic: "" },
  { unit: 4, group: 3, word: "think", meaning: "思考;想到", phonetic: "" },
  { unit: 4, group: 3, word: "clever", meaning: "聪明的", phonetic: "" },
  { unit: 4, group: 3, word: "idea", meaning: "想法", phonetic: "" },
  { unit: 4, group: 3, word: "jar", meaning: "广口瓶", phonetic: "" },
  { unit: 4, group: 3, word: "them", meaning: "他们", phonetic: "" },
  { unit: 4, group: 4, word: "these", meaning: "这些", phonetic: "" },
  { unit: 4, group: 4, word: "bucket", meaning: "桶", phonetic: "" },
  { unit: 4, group: 4, word: "pot", meaning: "锅", phonetic: "" },
  { unit: 4, group: 4, word: "hit", meaning: "打;击", phonetic: "" },
  { unit: 4, group: 4, word: "beautiful", meaning: "美妙的", phonetic: "" },
  { unit: 4, group: 5, word: "clap", meaning: "鼓掌", phonetic: "" },
  { unit: 4, group: 5, word: "musical instrument", meaning: "乐器", phonetic: "" },

  // Unit 5
  { unit: 5, group: 1, word: "paper-cut", meaning: "剪纸", phonetic: "" },
  { unit: 5, group: 1, word: "painting", meaning: "绘画", phonetic: "" },
  { unit: 5, group: 1, word: "circle", meaning: "圆形", phonetic: "" },
  { unit: 5, group: 1, word: "triangle", meaning: "三角形", phonetic: "" },
  { unit: 5, group: 1, word: "square", meaning: "正方形", phonetic: "" },
  { unit: 5, group: 2, word: "star", meaning: "星星", phonetic: "" },
  { unit: 5, group: 2, word: "rectangle", meaning: "矩形;长方形", phonetic: "" },
  { unit: 5, group: 2, word: "clock", meaning: "钟", phonetic: "" },
  { unit: 5, group: 2, word: "shape", meaning: "形状", phonetic: "" },
  { unit: 5, group: 2, word: "side", meaning: "边", phonetic: "" },
  { unit: 5, group: 3, word: "corner", meaning: "角", phonetic: "" },
  { unit: 5, group: 3, word: "ask", meaning: "问", phonetic: "" },
  { unit: 5, group: 3, word: "tiger", meaning: "老虎", phonetic: "" },
  { unit: 5, group: 3, word: "say", meaning: "说", phonetic: "" },

  // Unit 6
  { unit: 6, group: 1, word: "day", meaning: "天;白天", phonetic: "" },
  { unit: 6, group: 1, word: "night", meaning: "夜晚", phonetic: "" },
  { unit: 6, group: 1, word: "hour", meaning: "小时", phonetic: "" },
  { unit: 6, group: 1, word: "minute", meaning: "分钟", phonetic: "" },
  { unit: 6, group: 1, word: "second", meaning: "秒", phonetic: "" },
  { unit: 6, group: 2, word: "month", meaning: "月", phonetic: "" },
  { unit: 6, group: 2, word: "year", meaning: "年", phonetic: "" },
  { unit: 6, group: 2, word: "measure", meaning: "测量", phonetic: "" },
  { unit: 6, group: 2, word: "question", meaning: "问题", phonetic: "" },
  { unit: 6, group: 2, word: "around", meaning: "围绕", phonetic: "" },
  { unit: 6, group: 3, word: "exercise", meaning: "运动;锻炼", phonetic: "" },
  { unit: 6, group: 3, word: "get ready", meaning: "准备好", phonetic: "" },
  { unit: 6, group: 3, word: "at the same time", meaning: "同时", phonetic: "" },
  { unit: 6, group: 3, word: "What time is it?", meaning: "几点了?", phonetic: "" },

  // Unit 7
  { unit: 7, group: 1, word: "liquid", meaning: "液体", phonetic: "" },
  { unit: 7, group: 1, word: "solid", meaning: "固体", phonetic: "" },
  { unit: 7, group: 1, word: "gas", meaning: "气体", phonetic: "" },
  { unit: 7, group: 1, word: "sugar", meaning: "食糖", phonetic: "" },
  { unit: 7, group: 1, word: "salt", meaning: "盐", phonetic: "" },
  { unit: 7, group: 2, word: "cream", meaning: "奶油", phonetic: "" },
  { unit: 7, group: 2, word: "melt", meaning: "熔化;融化", phonetic: "" },
  { unit: 7, group: 2, word: "steam", meaning: "水蒸气", phonetic: "" },
  { unit: 7, group: 2, word: "heat", meaning: "加热", phonetic: "" },
  { unit: 7, group: 2, word: "hungry", meaning: "感到饿的", phonetic: "" },
  { unit: 7, group: 3, word: "party", meaning: "聚会;派对", phonetic: "" },
  { unit: 7, group: 3, word: "ice cream", meaning: "冰淇淋", phonetic: "" },
  { unit: 7, group: 3, word: "freezer", meaning: "冰柜", phonetic: "" },
  { unit: 7, group: 3, word: "door", meaning: "门", phonetic: "" },
  { unit: 7, group: 3, word: "open", meaning: "开着的", phonetic: "" },
  { unit: 7, group: 4, word: "plastic", meaning: "塑料的", phonetic: "" },
  { unit: 7, group: 4, word: "mix", meaning: "混合", phonetic: "" },
  { unit: 7, group: 4, word: "put", meaning: "放", phonetic: "" },
  { unit: 7, group: 4, word: "mixture", meaning: "混合物", phonetic: "" },
  { unit: 7, group: 4, word: "chocolate", meaning: "巧克力", phonetic: "" },
  { unit: 7, group: 5, word: "shake", meaning: "摇动", phonetic: "" },
  { unit: 7, group: 5, word: "freeze", meaning: "结冰;冻住", phonetic: "" },
  { unit: 7, group: 5, word: "Sure!", meaning: "当然!", phonetic: "" },
  { unit: 7, group: 5, word: "Don't worry!", meaning: "别担心!", phonetic: "" },
  { unit: 7, group: 5, word: "Done!", meaning: "做好了!", phonetic: "" },

  // Unit 8
  { unit: 8, group: 1, word: "polite", meaning: "有礼貌的", phonetic: "" },
  { unit: 8, group: 1, word: "take turns", meaning: "轮流", phonetic: "" },
  { unit: 8, group: 1, word: "knock", meaning: "敲击", phonetic: "" },
  { unit: 8, group: 1, word: "ox", meaning: "公牛", phonetic: "" },
  { unit: 8, group: 1, word: "until", meaning: "直到", phonetic: "" },
  { unit: 8, group: 2, word: "someone", meaning: "某人", phonetic: "" },
  { unit: 8, group: 2, word: "invite", meaning: "邀请", phonetic: "" },
  { unit: 8, group: 2, word: "behind", meaning: "在……之后", phonetic: "" },
  { unit: 8, group: 2, word: "maybe", meaning: "大概;可能", phonetic: "" },
  { unit: 8, group: 2, word: "cry", meaning: "哭泣", phonetic: "" },
  { unit: 8, group: 3, word: "kind", meaning: "友善的", phonetic: "" },
  { unit: 8, group: 3, word: "honey", meaning: "蜂蜜", phonetic: "" },
  { unit: 8, group: 3, word: "joke", meaning: "笑话", phonetic: "" },
  { unit: 8, group: 3, word: "whatever", meaning: "无论什么", phonetic: "" },
  { unit: 8, group: 3, word: "another", meaning: "另一个", phonetic: "" },
  { unit: 8, group: 4, word: "helpful", meaning: "愿意帮忙的", phonetic: "" },
  { unit: 8, group: 4, word: "way", meaning: "方法;方式", phonetic: "" },
  { unit: 8, group: 4, word: "May I come in?", meaning: "我可以进来吗?", phonetic: "" }
];